---
#- hosts: apiservers
  #sudo: yes
  #  remote_user: root
  # tasks:
           - name:  Copying script to server
             copy:
               src: backenddeploy/files/builddeploy.sh 
               dest: ~/
           - name: Executing the Script
             command: sh ~/builddeploy.sh
