---
          - name: Removing a Directory
            file:
                    path: '{{ dirapi }}'
                    state: absent
                    mode: 0775
            when: path == true


          - name: Creating a Directory
            file:
                    path: '{{ dirapi }}'
                    state: directory
                    mode: 0775
                    #      when: path == true

          - name: Cloning Source Code Repo
            git:
                    repo: https://ansible-story@dev.azure.com/ansible-story/springbootapp_pune/_git/springbootapp_pune
                    dest: '{{ dirapi }}'
                    version: branchcr7
					
               #   mode: 0775
            #when: webpath == true



          - name: Docker -  Building Image of the Application
            shell:
                cmd: docker build -t api:1.0 .
                # when: Dockerfile == true
                chdir: '{{ apiDockerfile }}'

          - name: Docker - Checking if any containers running on the target port ad stopping it.
            shell: 
              cmd: docker stop $(docker ps | grep '{{ portapi }}' | awk '{print $1}')
              #when:
            ## debug:
                    #       msg: "container on port '{{ port }}' stopped"

          - name: Docker - Running the Container
            shell:
                    cmd: docker run -d -p '{{ portapi }}':'{{ exposeapi }}' api:1.0
                    #  debug:
